% Copyright (c) 2009-2012 Thomas Schaffter
% 
% We release this software open source under an MIT license (see below). If this
% software was useful for your scientific work, please cite our paper(s) listed
% on http://tschaffter.ch/projects/libsde.
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in
% all copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
% THE SOFTWARE.

% n is the number of stochastic equations
function example(n)

% load time series data generated by the main method of the class
% TimeSeriesExperiment in libSDE
X = load('../mySDE_timeseries.tsv');
t = X(:,1); % extract time scale

% plot all the n trajectories
for i=1:n
   X1 = X(:,i+1);
   plot(t,X1,'-');
   hold on;
end

hold on

% plot the exact solution in high resolution
t = 0:0.00001:1;
s = 2/3 *exp(-3*t) + 1/3;
plot(t,s, 'r');
axis([0 1 0 1.2])

title('50 solutions X of dX = (-3X+1)dt + sigma*dW with X(0) = 1 and sigma = 0.2')
xlabel('Time (a.u.)');
ylabel('X');

end
